services:
  db:
    image: postgres:15-alpine
    container_name: noti_fin_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-noti_fin}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: ghcr.io/${DOCKER_IMAGE_NAME}:latest
    container_name: noti_fin_bot
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-noti_fin}
    depends_on:
      - db
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    command: sh -c "alembic upgrade head && python main.py"

  caddy:
    image: caddy:latest
    container_name: noti_fin_proxy
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
