"""Initial schema

Revision ID: 2de405b771ec
Revises: 
Create Date: 2026-04-09 10:25:17.604596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de405b771ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('notion_access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('notion_refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('notion_bot_id', sa.String(length=100), nullable=True),
    sa.Column('notion_workspace_id', sa.String(length=100), nullable=True),
    sa.Column('notion_workspace_name', sa.String(length=255), nullable=True),
    sa.Column('accounts_db_id', sa.String(length=100), nullable=True),
    sa.Column('expenses_db_id', sa.String(length=100), nullable=True),
    sa.Column('group_expenses_db_id', sa.String(length=100), nullable=True),
    sa.Column('categories_db_id', sa.String(length=100), nullable=True),
    sa.Column('oauth_state', sa.String(length=255), nullable=True),
    sa.Column('oauth_state_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_oauth_state'), 'users', ['oauth_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oauth_state'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
