"""Add notion_template_name to users

Revision ID: 6fd2eed6c36c
Revises: edda6dfd829b
Create Date: 2026-04-11 16:06:47.789182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd2eed6c36c'
down_revision: Union[str, Sequence[str], None] = 'edda6dfd829b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notion_template_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notion_template_name')
    # ### end Alembic commands ###
