"""Add stats_page_id to User

Revision ID: edda6dfd829b
Revises: 678d31913e7a
Create Date: 2026-04-09 16:27:46.876712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edda6dfd829b'
down_revision: Union[str, Sequence[str], None] = '678d31913e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stats_page_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stats_page_id')
    # ### end Alembic commands ###
