name: Deploy to DigitalOcean

on:
  push:
    tags:
      - '*'


jobs:
  deploy:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Remove unnecessary files
        run: rm -rf .venv .git __pycache__ .pytest_cache tests README.md README.dev.md .github

      - name: Copy files to droplets via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/noti-fin-bot"
          rm: true
          timeout: 5m
          command_timeout: 10m

      - name: Lowercase repo name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        env:
          APP_VERSION: ${{ github.ref_name }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ env.REPO_LOWER }}
        with:

          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: APP_VERSION,GHCR_TOKEN,GITHUB_ACTOR,GITHUB_REPOSITORY
          script: |
            cd ~/noti-fin-bot
            
            # Login to GitHub Container Registry
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin

            # Create .env file with all necessary variables
            cat <<EOF > .env
            GITHUB_REPOSITORY=$GITHUB_REPOSITORY
            # Telegram
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            
            # Gemini
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            
            # Database
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            DATABASE_URL=postgresql+asyncpg://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@db:5432/${{ secrets.DB_NAME }}
            
            # Security
            FERNET_KEY=${{ secrets.FERNET_KEY }}
            
            # Notion OAuth
            NOTION_CLIENT_ID=${{ secrets.NOTION_CLIENT_ID }}
            NOTION_CLIENT_SECRET=${{ secrets.NOTION_CLIENT_SECRET }}
            NOTION_REDIRECT_URI=${{ secrets.NOTION_REDIRECT_URI }}
            
            # AWS S3
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            
            # Caddy / Domain
            DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
            
            # Server & Environment
            PORT=${{ secrets.PORT }}
            ENV=prod
            VERSION=$APP_VERSION
            RELEASE_NOTES_URL=${{ secrets.RELEASE_NOTES_URL }}
            EOF
            
            # Pull new image and restart services
            docker compose pull
            docker compose up -d
